**New Notebook - Streamline**

In [10]:
#import packages
#standard packages
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import re
%matplotlib inline
# bag of words
from sklearn.feature_extraction.text import CountVectorizer
# stemming and lemmatizing
import nltk
nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('punkt')

from nltk.tokenize import word_tokenize #makes tokens
from nltk.stem import PorterStemmer #word stemming
from nltk.stem import WordNetLemmatizer #lemmatizer
from nltk.corpus import stopwords #remove stopwords 
from nltk.sentiment.vader import SentimentIntensityAnalyzer #sentiment analysis

##support vector machine package
from sklearn import svm 
#evaulation metrics
from sklearn import metrics
from sklearn import tree

import nltk
nltk.download('vader_lexicon')

#testing and training set splitting function
from sklearn.model_selection import train_test_split

import re ##regular expressions package that allows us to remove punctuation and change capitalization (among other things)
import string ## package that deals with string operations


[nltk_data] Downloading package wordnet to /home/jupyter/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /home/jupyter/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /home/jupyter/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /home/jupyter/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!


In [5]:
#------------------------ NLP ------------------------------------------#

In [4]:
filename = "NL-classification.csv"
df = pd.read_csv(filename)

text = df['Text'].tolist()
print(text[slice(10)])

example_text_1 = text

lemmatizer = WordNetLemmatizer()
stop_words = stopwords.words('english')
pattern = r'[0-9]'

new_list = []
replace = []

for s in example_text_1:
    s = s.lower()
    s = re.sub(pattern, '', s)
    s = re.sub(r'[^\w\s]','', s)
    s = word_tokenize(s)
    for word in s:
        if word not in stop_words:
            replace.append(lemmatizer.lemmatize(word))
    re2 = " ".join(replace)
    new_list.append(re2)
    replace = []


#print(new_list[slice(5)])

# use bag of words to turn text into a vector
vectorizer = CountVectorizer()
text_vectors = vectorizer.fit_transform(new_list)

print(vectorizer.get_feature_names_out())
print(text_vectors.toarray())

##------------------------------------------------------------------------------------------##
## Now let's try some of our own sentences that aren't already classified
sent1 = "I enjoyed a successful evening cupcake with my grandchildren" #bonding
sent2 = "I happy bread, surprising myself with a spectacular recipe"   #achievement
sent3 = "I went on walk"                                               #exercise

new_sentences = [sent1, sent2, sent3]

new_list2 = []
replace2 = []

for s in new_sentences:
    s = s.lower()
    s = re.sub(pattern, '', s)
    s = re.sub(r'[^\w\s]','', s)
    s = word_tokenize(s)
    for word in s:
        if word not in stop_words:
            replace2.append(lemmatizer.lemmatize(word))
    re3 = " ".join(replace2)
    new_list2.append(re3)
    replace2 = []


#print(new_list2[slice(5)])

# use bag of words to turn text into a vector
new_vectors = vectorizer.transform(new_list2)

print(vectorizer.get_feature_names_out())
print(text_vectors.toarray())

##NEW SENTENCES called "new_vectors" -> these are sentences that have not been included in either training or testing data


##This is the sentiment analysis base code...   can be implemented into more complex things
analyzer = SentimentIntensityAnalyzer()
score = analyzer.polarity_scores("I hate everything")
total_score = score['pos'] - score['neg']
com_score = score['compound']
print(com_score)
print(total_score)

['I went on a successful date with someone I felt sympathy and connection with.', 'I was happy when my son got 90% marks in his examination', 'I went to the gym this morning and did yoga.', 'We had a serious talk with some friends of ours who have been flaky lately. They understood and we had a good evening hanging out.', 'I went with grandchildren to butterfly display at Crohn Conservatory', 'I meditated last night.', 'I made a new recipe for peasant bread, and it came out spectacular!', 'I got gift from my elder brother which was really surprising me', 'YESTERDAY MY MOMS BIRTHDAY SO I ENJOYED', 'Watching cupcake wars with my three teen children']
['aadhar' 'aagra' 'aare' ... 'zootopia' 'zumba' 'zverev']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
['aadhar' 'aagra' 'aare' ... 'zootopia' 'zumba' 'zverev']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0

In [6]:
#------------------------------------ ML ---------------------------------------

In [9]:
#All emotion lists
labels = df['Label'].tolist()
#print(labels[slice(5)])

emotion_list = []

for e in labels:
    if e == "affection":
        emotion_list.append(1)
    else:
        emotion_list.append(0)

#print(emotion_list[slice(10)])

exercise_list = []

for e in labels:
    if e == "exercise":
        exercise_list.append(1)
    else:
        exercise_list.append(0)
